Add better handling in scenario where Homebrew can't uninstall package.
kickstarter/laptop pull request #44
Opened 2017-02-08 17:17 UTC by frewsxcv

Yesterday I installed the 'yarn' package via Homebrew. It has a
dependency on the 'node' package. I ran `bin/dev` today and it failed
without an error message. This is because the laptop script attempts to
uninstall Homebrew's 'node' package, but it could not because the 'yarn'
package has a dependency on it.

Prior to this commit, if Homebrew encounters an error, we redirect them
to `/dev/null`, which is why I didn't have any idea what the issue was.

With the changes in this commit, I added more logging when we uninstall
a Homebrew package and only redirect stdout (not stderr) to `/dev/null`.

2017-02-08 17:56 UTC, frewsxcv commented
Adding reviewers that were recent contributors to the script

2017-02-08 21:25 UTC, ktheory requested changes
Nice catch, @frewsxcv.

We ran in to a similar problem with wanting to see output on errors in #41, and made a way to show output on failure by piping to `$tmp_output`.

Whatcha think about changing the original commands to pipe to `$tmp_output` instead of `/dev/null` ?

2017-02-10 15:36 UTC, frewsxcv commented
> https://github.com/kickstarter/laptop/pull/44#pullrequestreview-20872714

Good idea! Addressed in https://github.com/kickstarter/laptop/pull/44/commits/c268b04796ee716029d4aa469af3db0e3effe996.

2017-02-13 14:57 UTC, frewsxcv commented
@ktheory Have any other thoughts about this?

2017-02-13 15:34 UTC, ktheory approved these changes
Beautiful. 👍

2017-02-13 15:35 UTC, merged